image: python:latest

variables:
    IMAGE_NAME: kejsiblushi/djangoapp
    IMAGE_TAG: latest
 
before_script:
  - docker info
  
stages:
    - build

build_image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
        - docker push $DOCKER_REGISTRY_USER/$IMAGE_NAME:$(git log -1 --format=%h)

    tags:
        - "docker"
