image: python:latest

variables:

    IMAGE_NAME: kejsiblushi/djangoapp
    IMAGE_TAG: latest

stages:
    -build

build_image :
  image : docker:latest
  stage: build
  services:
    - docker:dind

  variables:
   DOCKER_TLS_CERTDIT: "/certs"

  script:
      - docker info
      - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" 
      - docker build -t  $IMAGE_NAME:$IMAGE_TAG .
      - docker push $IMAGE_NAME:$IMAGE_TAG-1.0

