image: python:latest

variables:
    IMAGE_NAME: kejsiblushi/djangoapp
    IMAGE_TAG: latest
 
before_script:
  - docker info
  
stages:
    - build

build_image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
        - docker build -t $IMAGE_NAME:$(git log -1 --format=%h) .
        - docker push $IMAGE_NAME:$(git log -1 --format=%h)

    rules: 
        - if: '$CI_COMMIT_BRANCH == "main"' 
          when: always 
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"' 
          when: always

    tags:
        - "docker"
