image: python:latest

variables:
    IMAGE_NAME: kejsiblushi/djangoapp
    IMAGE_TAG: latest
 

stages:
    - build

build_image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - sudo docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
        - sudo docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - sudo docker push $IMAGE_NAME:$IMAGE_TAG
